export const ANTIBIOTICS = [
  // Level 1 — Skin
  {
    id: 'flucloxacillin',
    name: 'Flucloxacillin',
    class: 'Beta-lactam (penicillinase-resistant)',
    coverage: ['Staph aureus (MSSA)'],
    level: 1,
    cost: 0,
    unlocked: false,
    description: 'First-line for MSSA skin infections. Narrow spectrum.',
  },
  {
    id: 'vancomycin',
    name: 'Vancomycin',
    class: 'Glycopeptide',
    coverage: ['MRSA', 'Staph aureus', 'Enterococcus'],
    level: 1,
    cost: 50,
    unlocked: false,
    description: 'Reserved for MRSA. IV only. Monitor levels.',
  },
  {
    id: 'clindamycin',
    name: 'Clindamycin',
    class: 'Lincosamide',
    coverage: ['Staph aureus (some MRSA)', 'Streptococcus', 'Anaerobes'],
    level: 1,
    cost: 30,
    unlocked: false,
    description: 'Good skin/soft tissue penetration. Check local resistance.',
  },
  // Level 2 — Respiratory
  {
    id: 'amoxicillin',
    name: 'Amoxicillin',
    class: 'Beta-lactam (aminopenicillin)',
    coverage: ['H. influenzae (non-resistant)', 'Strep pneumoniae', 'Kingella'],
    level: 2,
    cost: 20,
    unlocked: false,
    description: 'First-line for community pneumonia. Also covers Kingella (Level 6).',
  },
  {
    id: 'doxycycline',
    name: 'Doxycycline',
    class: 'Tetracycline',
    coverage: ['H. influenzae', 'Atypicals', 'MRSA (some)'],
    level: 2,
    cost: 25,
    unlocked: false,
    description: 'Atypical cover. Oral option for CAP.',
  },
  {
    id: 'rifampicin_isoniazid',
    name: 'Rifampicin + Isoniazid',
    class: 'Anti-tuberculosis (RIPE therapy)',
    coverage: ['Mycobacterium tuberculosis'],
    level: 2,
    cost: 80,
    unlocked: false,
    description: 'Core of TB treatment. Must combine to prevent resistance. 6+ months.',
  },
  // Level 3 — GI
  {
    id: 'triple_therapy',
    name: 'Triple Therapy (Amox + Clarithromycin + PPI)',
    class: 'H. pylori eradication',
    coverage: ['H. pylori'],
    level: 3,
    cost: 40,
    unlocked: false,
    description: '7-day course. Test and treat.',
  },
  {
    id: 'metronidazole',
    name: 'Metronidazole',
    class: 'Nitroimidazole',
    coverage: ['C. difficile (mild)', 'Anaerobes', 'H. pylori'],
    level: 3,
    cost: 20,
    unlocked: false,
    description: 'First-line for mild C. diff. Also covers anaerobes.',
  },
  // Level 4 — Urinary
  {
    id: 'trimethoprim',
    name: 'Trimethoprim',
    class: 'Dihydrofolate reductase inhibitor',
    coverage: ['E. coli', 'Klebsiella (some)'],
    level: 4,
    cost: 15,
    unlocked: false,
    description: 'First-line for uncomplicated UTI. Oral.',
  },
  {
    id: 'nitrofurantoin',
    name: 'Nitrofurantoin',
    class: 'Nitrofuran',
    coverage: ['E. coli', 'Enterococcus'],
    level: 4,
    cost: 15,
    unlocked: false,
    description: 'Lower UTI only — poor tissue penetration. Avoid in pyelonephritis.',
  },
  {
    id: 'ciprofloxacin',
    name: 'Ciprofloxacin',
    class: 'Fluoroquinolone',
    coverage: ['Pseudomonas', 'E. coli', 'Gram-negatives'],
    level: 4,
    cost: 60,
    unlocked: false,
    description: 'Best oral option for Pseudomonas UTI. Also covers pyelonephritis.',
  },
  // Level 5 — Musculoskeletal
  {
    id: 'flucloxacillin_bone',
    name: 'Flucloxacillin (bone)',
    class: 'Beta-lactam',
    coverage: ['Staph aureus (MSSA) bone/joint'],
    level: 5,
    cost: 0,
    unlocked: false,
    description: 'IV for acute osteomyelitis. Long courses (4-6 weeks).',
  },
  {
    id: 'vancomycin_bone',
    name: 'Vancomycin (MRSA bone)',
    class: 'Glycopeptide',
    coverage: ['MRSA osteomyelitis', 'PJI'],
    level: 5,
    cost: 70,
    unlocked: false,
    description: 'For MRSA bone/joint. Monitor levels closely.',
  },
  // Level 6 — Cardiovascular / IE
  {
    id: 'benzylpenicillin',
    name: 'Benzylpenicillin',
    class: 'Beta-lactam (natural penicillin)',
    coverage: ['Strep viridans', 'Strep pneumoniae'],
    level: 6,
    cost: 30,
    unlocked: false,
    description: 'IV penicillin for Strep viridans IE. 4-6 weeks.',
  },
  {
    id: 'vancomycin_gent',
    name: 'Vancomycin + Gentamicin',
    class: 'Glycopeptide + Aminoglycoside',
    coverage: ['Staph aureus IE (MRSA)', 'Enterococcus IE'],
    level: 6,
    cost: 100,
    unlocked: false,
    description: 'Combination for Staph A IE. Monitor renal function and levels.',
  },
];

export const ENEMIES = {
  mrsa_cellulitis: {
    id: 'mrsa_cellulitis',
    name: 'MRSA Cellulitis',
    gramStain: 'Gram-positive cocci (clusters)',
    morphology: 'Staphylococcus aureus (MRSA)',
    firstLine: 'Vancomycin (IV) / Clindamycin / TMP-SMX',
    level: 1,
    color: '#e63946',
    size: 28,
    health: 3,
    speed: 1.2,
    antibodyReward: 15,
    description: 'Methicillin-resistant S. aureus. Resistant to beta-lactams. Look for purulent skin lesion.',
  },
  staph_aureus: {
    id: 'staph_aureus',
    name: 'Staph Aureus',
    gramStain: 'Gram-positive cocci (clusters)',
    morphology: 'Staphylococcus aureus',
    firstLine: 'Flucloxacillin (MSSA)',
    level: 1,
    color: '#f4a261',
    size: 22,
    health: 2,
    speed: 1.5,
    antibodyReward: 8,
    description: 'MSSA henchman. Common skin pathogen.',
  },
  h_influenzae: {
    id: 'h_influenzae',
    name: 'H. Influenzae',
    gramStain: 'Gram-negative coccobacillus',
    morphology: 'Haemophilus influenzae',
    firstLine: 'Amoxicillin / Doxycycline',
    level: 2,
    color: '#e76f51',
    size: 18,
    health: 1,
    speed: 2.0,
    antibodyReward: 6,
    description: 'Respiratory henchman. Typical pneumonia pathogen.',
  },
  tb: {
    id: 'tb',
    name: 'Mycobacterium Tuberculosis',
    gramStain: 'Acid-fast bacillus (neither gram +/-)',
    morphology: 'M. tuberculosis',
    firstLine: 'RIPE therapy (6+ months)',
    level: 2,
    color: '#6d6875',
    size: 35,
    health: 8,
    speed: 0.8,
    antibodyReward: 50,
    description: 'Boss of Level 2. Slow-growing. Requires long-course combination therapy.',
  },
  e_coli: {
    id: 'e_coli',
    name: 'E. Coli',
    gramStain: 'Gram-negative rod',
    morphology: 'Escherichia coli',
    firstLine: 'Trimethoprim / Ciprofloxacin',
    level: 3,
    color: '#2a9d8f',
    size: 20,
    health: 2,
    speed: 1.8,
    antibodyReward: 8,
    description: 'Most common UTI pathogen. Also GI pathogen.',
  },
  c_diff: {
    id: 'c_diff',
    name: 'C. Difficile',
    gramStain: 'Gram-positive rod (spore-forming)',
    morphology: 'Clostridioides difficile',
    firstLine: 'Metronidazole → Oral Vancomycin → Fidaxomicin',
    level: 3,
    color: '#e9c46a',
    size: 32,
    health: 6,
    speed: 1.0,
    antibodyReward: 40,
    description: 'Boss of Level 3. Antibiotic-associated. Produces toxins A and B.',
  },
  pseudomonas: {
    id: 'pseudomonas',
    name: 'Pseudomonas Aeruginosa',
    gramStain: 'Gram-negative rod',
    morphology: 'Pseudomonas aeruginosa',
    firstLine: 'Ciprofloxacin / Piperacillin-Tazobactam / Meropenem',
    level: 4,
    color: '#52b788',
    size: 38,
    health: 10,
    speed: 1.4,
    antibodyReward: 60,
    description: 'Boss of Level 4. Intrinsically resistant to many antibiotics. ICU pathogen.',
  },
  strep_viridans: {
    id: 'strep_viridans',
    name: 'Strep Viridans',
    gramStain: 'Gram-positive cocci (chains)',
    morphology: 'Viridans group Streptococcus',
    firstLine: 'Benzylpenicillin (IE)',
    level: 6,
    color: '#90e0ef',
    size: 30,
    health: 6,
    speed: 1.2,
    antibodyReward: 35,
    description: 'IE boss phase 1. Subacute endocarditis. Dental procedure association.',
  },
  kingella: {
    id: 'kingella',
    name: 'Kingella',
    gramStain: 'Gram-negative coccobacillus',
    morphology: 'Kingella kingae',
    firstLine: 'Amoxicillin',
    level: 6,
    color: '#a8dadc',
    size: 28,
    health: 5,
    speed: 1.5,
    antibodyReward: 35,
    description: 'IE boss phase 3. HACEK organism. Unusual but sensitive to penicillins.',
  },
};

export const POWER_UPS = {
  macrophage: {
    id: 'macrophage',
    name: 'Macrophage',
    description: 'Player grows large — increased damage and knockback',
    duration: 8000,
    color: '#f77f00',
  },
  filgrastim: {
    id: 'filgrastim',
    name: 'Filgrastim (G-CSF)',
    description: 'Spawns 3 soldier T cells to fight alongside you',
    duration: 10000,
    color: '#4cc9f0',
  },
  steroid: {
    id: 'steroid',
    name: 'Corticosteroid',
    description: 'All on-screen enemies weakened — take double damage',
    duration: 6000,
    color: '#f72585',
  },
};

export const LEVELS = [
  {
    id: 1,
    name: 'Skin',
    subtitle: 'MRSA Cellulitis',
    description: 'Defend the skin barrier against MRSA and Staph aureus infection.',
    unlocked: true,
    color: '#e63946',
    bgColor: '#1a0a0a',
    boss: 'mrsa_cellulitis',
    henchmen: ['staph_aureus'],
    antibioticRewards: ['flucloxacillin', 'vancomycin', 'clindamycin'],
  },
  {
    id: 2,
    name: 'Respiratory',
    subtitle: 'Tuberculosis',
    description: 'Fight through the airways against H. influenzae and TB.',
    unlocked: false,
    color: '#4361ee',
    bgColor: '#0a0a1a',
    boss: 'tb',
    henchmen: ['h_influenzae'],
    antibioticRewards: ['amoxicillin', 'doxycycline', 'rifampicin_isoniazid'],
  },
  {
    id: 3,
    name: 'Gastrointestinal',
    subtitle: 'C. Difficile',
    description: 'Navigate the GI tract with moving peristalsis floors.',
    unlocked: false,
    color: '#f4a261',
    bgColor: '#1a0f00',
    boss: 'c_diff',
    henchmen: ['e_coli'],
    antibioticRewards: ['triple_therapy', 'metronidazole'],
  },
  {
    id: 4,
    name: 'Urinary',
    subtitle: 'Pseudomonas',
    description: 'Underwater world with decreasing visibility.',
    unlocked: false,
    color: '#52b788',
    bgColor: '#001a0a',
    boss: 'pseudomonas',
    henchmen: ['e_coli'],
    antibioticRewards: ['trimethoprim', 'nitrofurantoin', 'ciprofloxacin'],
  },
  {
    id: 5,
    name: 'Musculoskeletal',
    subtitle: 'MRSA Osteomyelitis',
    description: 'Bone and joint terrain with fragile osteoporotic ground.',
    unlocked: false,
    color: '#e9c46a',
    bgColor: '#1a1400',
    boss: 'mrsa_cellulitis',
    henchmen: ['staph_aureus'],
    antibioticRewards: ['flucloxacillin_bone', 'vancomycin_bone'],
  },
  {
    id: 6,
    name: 'Cardiovascular',
    subtitle: 'Infective Endocarditis',
    description: '3-phase boss fight inside the heart. Sepsis 6 the final challenge.',
    unlocked: false,
    color: '#e63946',
    bgColor: '#1a0005',
    boss: 'strep_viridans',
    henchmen: ['e_coli', 'staph_aureus', 'pseudomonas'],
    antibioticRewards: ['benzylpenicillin', 'vancomycin_gent', 'amoxicillin'],
  },
];

export const HINTS = [
  { id: 'h1', level: 1, title: 'Gram Stain Basics', text: 'Gram-positive = purple (thick peptidoglycan wall). Gram-negative = pink/red (thin wall + outer membrane). Guides antibiotic choice.' },
  { id: 'h2', level: 1, title: 'MRSA vs MSSA', text: 'MRSA = Methicillin-Resistant Staph Aureus. Resistant to all beta-lactams. Use vancomycin or clindamycin instead of flucloxacillin.' },
  { id: 'h3', level: 1, title: 'Skin Infection Signs', text: 'Cellulitis: non-purulent, spreading redness, warmth. SSTI: treat empirically with beta-lactams unless MRSA risk factors.' },
  { id: 'h4', level: 2, title: 'Typical vs Atypical Pneumonia', text: 'Typical (S. pneumoniae): lobar consolidation, productive cough. Atypical (Mycoplasma, Legionella): bilateral infiltrates, dry cough. Cover both with doxycycline.' },
  { id: 'h5', level: 2, title: 'TB Treatment (RIPE)', text: 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol for 2 months, then Rifampicin + Isoniazid for 4 months. Never monotherapy.' },
  { id: 'h6', level: 3, title: 'C. Diff Risk Factors', text: 'Recent antibiotics (esp. cephalosporins, clindamycin, fluoroquinolones), PPI use, hospital admission, elderly. Stop precipitating antibiotic if possible.' },
  { id: 'h7', level: 3, title: 'C. Diff Treatment Ladder', text: 'Mild: metronidazole. Moderate-severe: oral vancomycin. Severe/recurrent: fidaxomicin. FMT for refractory cases.' },
  { id: 'h8', level: 4, title: 'UTI vs Pyelonephritis', text: 'Lower UTI: frequency, dysuria, suprapubic pain. Pyelonephritis: fever, loin pain, rigors. Urosepsis: systemic features. Escalate antibiotics accordingly.' },
  { id: 'h9', level: 4, title: 'Pseudomonas Risk', text: 'Suspect Pseudomonas in: ICU patients, immunocompromised, bronchiectasis, CF, recent antibiotics. Requires anti-pseudomonal cover.' },
  { id: 'h10', level: 5, title: 'Osteomyelitis', text: 'Staph aureus is the most common cause. Haematogenous spread in children. Direct spread in adults (diabetic foot, post-op). Long IV courses required (4-6 weeks).' },
  { id: 'h11', level: 6, title: 'Sepsis 6', text: 'Within 1 hour: 1. Blood cultures. 2. IV antibiotics. 3. IV fluid bolus. 4. Measure lactate. 5. Measure urine output. 6. High-flow oxygen.' },
  { id: 'h12', level: 6, title: 'IE Organisms by Valve', text: 'Native valve: Strep viridans (subacute), Staph aureus (acute). Prosthetic valve: Staph epidermidis (early), Staph aureus (late). IVDU: right-sided (tricuspid), Staph aureus.' },
];

export const MCS_REPORTS = [
  {
    id: 'mcs1',
    level: 1,
    title: 'Skin Swab — MRSA',
    organism: 'Staphylococcus aureus (MRSA)',
    sensitive: ['Vancomycin', 'Clindamycin', 'TMP-SMX', 'Linezolid'],
    resistant: ['Flucloxacillin', 'Penicillin', 'Amoxicillin', 'Cephalosporins'],
    recommendation: 'Use vancomycin (IV) or clindamycin (if susceptible) for MRSA skin infection.',
  },
  {
    id: 'mcs2',
    level: 2,
    title: 'Sputum MCS — TB',
    organism: 'Mycobacterium tuberculosis',
    sensitive: ['Rifampicin', 'Isoniazid', 'Pyrazinamide', 'Ethambutol'],
    resistant: [],
    recommendation: 'Initiate RIPE therapy. Notify public health. Contact tracing required.',
  },
  {
    id: 'mcs3',
    level: 3,
    title: 'Stool MCS — C. Diff',
    organism: 'Clostridioides difficile (toxin A+B positive)',
    sensitive: ['Metronidazole', 'Oral Vancomycin', 'Fidaxomicin'],
    resistant: [],
    recommendation: 'Stop precipitating antibiotic. Start metronidazole (mild) or oral vancomycin (severe).',
  },
  {
    id: 'mcs4',
    level: 4,
    title: 'Urine MCS — Pseudomonas',
    organism: 'Pseudomonas aeruginosa',
    sensitive: ['Ciprofloxacin', 'Piperacillin-tazobactam', 'Meropenem', 'Gentamicin'],
    resistant: ['Trimethoprim', 'Nitrofurantoin', 'Amoxicillin', 'Cephalexin'],
    recommendation: 'Use ciprofloxacin (oral) or pip-tazo (IV). Avoid narrow-spectrum agents.',
  },
];
